<form action="<?php echo Mage::getUrl('cookieater/cookieater/setCookie') ?>" method="post">
<div class="ce-cookieform">
	<div class="ce-row">
		<div class="ce-inputfield">
			<input type="checkbox" name="accept-tech" id="accept-tech" value="accept-tech" checked="checked" readonly="readonly" disabled />
		</div>
		<div class="ce-input-description">
			<?php echo $this->__('<strong>Technical cookies:</strong> necessaries for the website to work properly.'); ?>
		</div>
		<div class="ce-clear"></div>
	</div>

	<div class="ce-row">
		<div class="ce-inputfield">
			<input type="checkbox" name="accept-prof" id="accept-prof" value="accept-prof" <?php if($this->getIsChecked('accept-prof')) echo 'checked="checked"'; ?>/>
		</div>
		<div class="ce-input-description">
			<?php echo $this->__('<strong>Profiling cookies:</strong> these cookies are used to remember about you and your preferences, in order to offer you a better experience and suggest you products which might interest you.'); ?>
		</div>
		<div class="ce-clear"></div>
	</div>

	<div class="ce-row">
		<div class="ce-inputfield">
			<input type="checkbox" name="accept-third" id="accept-third" value="accept-third" <?php if($this->getIsChecked('accept-third')) echo 'checked="checked"'; ?> />
		</div>
		<div class="ce-input-description">
			<?php echo $this->__('<strong>Third-parties cookies:</strong> these cookies are installed by subjects out of our control, like Google, or Facebook. Generally they are used to collect information and provide targeted advertising'); ?>
		</div>
		<div class="ce-clear"></div>
	</div>
	<div class="ce-row">
		<div class="ce-input-submit">
			<input type="submit" value="<?php echo $this->__('Save cookies preferences') ?>" ?>
		</div>
		<div class="ce-clear"></div>
	</div>
</div>
</form>