<?php
/**
 * Ep Cookieater Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Ep
 * @package	Ep_Cookieater
 * @copyright	Copyright (c) 2015 Enzo Perrotta (http://www.enzoperrotta.it)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * @category   Cookies Blocker
 * @package    Ep_Cookieater
 * @author     Enzo Perrotta
 * @property   Enzo Perrotta
 * @copyright  Copyright (c) 2015 Enzo Perrotta (http://www.enzoperrotta.it)
 */
?>
<?php if($this->isActionRequired()): ?>
<div class="ce-popup">
	<div class="ce-textblock">
		<?php echo $this->getPopupContent(); ?>
	</div>
	<div class="ce-buttonarea">
		<button type="button" title="<?php echo $this->__('More info and settings') ?>" onclick="showExtendedInfo()">
			<span><?php echo $this->__('More info and settings') ?></span>
		</button>
		<button type="button" title="<?php echo $this->__('Accept and continue') ?>" onclick="acceptCookies()">
			<span><?php echo $this->__('Accept and continue') ?></span>
		</button>
	</div>
</div>
<script type="text/javascript">
	function acceptCookies() {
		top.location.href = '<?php echo Mage::getUrl('cookieater/cookieater/setCookie', array('accept-all' => 'accept-all')) ?>';
	}
	function showExtendedInfo() {
		top.location.href = '<?php echo Mage::getUrl(Mage::getStoreConfig('cookieater_options/cookieater_configuration/policy_page')) ?>';
	}
</script>
<?php endif; ?>
<?php

/*
if (isset($_SERVER['HTTP_COOKIE'])) {
	$cookies = explode(';', $_SERVER['HTTP_COOKIE']);
	foreach($cookies as $cookie) {
		$parts = explode('=', $cookie);
		$name = trim($parts[0]);
		setcookie($name, '', time()-1000);
		setcookie($name, '', time()-1000, '/');
	}
}
*/